/* This file is auto-generated from design tokens. */
/* Do not edit this file manually. */

export const lightTheme = {
  "color": {
    "purple": {
      "25": "var(--color-purple-25)",
      "50": "var(--color-purple-50)",
      "100": "var(--color-purple-100)",
      "200": "var(--color-purple-200)",
      "300": "var(--color-purple-300)",
      "500": "var(--color-purple-500)",
      "600": "var(--color-purple-600)",
      "700": "var(--color-purple-700)",
      "750": "var(--color-purple-750)",
      "800": "var(--color-purple-800)",
      "900": "var(--color-purple-900)",
      "950": "var(--color-purple-950)"
    },
    "blue": {
      "400": "var(--color-blue-400)",
      "500": "var(--color-blue-500)"
    },
    "teal": {
      "50": "var(--color-teal-50)",
      "100": "var(--color-teal-100)",
      "300": "var(--color-teal-300)",
      "500": "var(--color-teal-500)",
      "700": "var(--color-teal-700)",
      "800": "var(--color-teal-800)",
      "900": "var(--color-teal-900)"
    },
    "slate": {
      "100": "var(--color-slate-100)",
      "600": "var(--color-slate-600)",
      "700": "var(--color-slate-700)",
      "800": "var(--color-slate-800)",
      "900": "var(--color-slate-900)"
    },
    "neutral": {
      "0": "var(--color-neutral-0)",
      "50": "var(--color-neutral-50)",
      "100": "var(--color-neutral-100)",
      "300": "var(--color-neutral-300)",
      "400": "var(--color-neutral-400)",
      "500": "var(--color-neutral-500)",
      "700": "var(--color-neutral-700)",
      "800": "var(--color-neutral-800)",
      "900": "var(--color-neutral-900)"
    },
    "glass": {
      "white16": "var(--color-glass-white16)",
      "white72": "var(--color-glass-white72)"
    },
    "brand": {
      "primary": "var(--color-brand-primary)",
      "primaryHover": "var(--color-brand-primary-hover)",
      "primaryActive": "var(--color-brand-primary-active)",
      "secondary": "var(--color-brand-secondary)",
      "soft": "var(--color-brand-soft)",
      "subtle": "var(--color-brand-subtle)"
    },
    "accent": {
      "primary": "var(--color-accent-primary)",
      "deep": "var(--color-accent-deep)",
      "soft": "var(--color-accent-soft)",
      "subtle": "var(--color-accent-subtle)"
    },
    "background": {
      "page": "var(--color-background-page)",
      "card": "var(--color-background-card)",
      "cardStrong": "var(--color-background-card-strong)"
    },
    "surface": {
      "primary": "var(--color-surface-primary)",
      "secondary": "var(--color-surface-secondary)",
      "featurePanel": "var(--color-surface-feature-panel)",
      "featureCard": "var(--color-surface-feature-card)",
      "featureCardDark": "var(--color-surface-feature-card-dark)"
    },
    "text": {
      "primary": "var(--color-text-primary)",
      "secondary": "var(--color-text-secondary)",
      "tertiary": "var(--color-text-tertiary)",
      "inverse": "var(--color-text-inverse)",
      "brand": "var(--color-text-brand)",
      "accent": "var(--color-text-accent)"
    },
    "border": {
      "default": "var(--color-border-default)",
      "strong": "var(--color-border-strong)",
      "focus": "var(--color-border-focus)",
      "accent": "var(--color-border-accent)",
      "feature": "var(--color-border-feature)"
    }
  },
  "fontFamilies": {
    "base": "var(--font-families-base)",
    "fallback": "var(--font-families-fallback)"
  },
  "fontWeights": {
    "regular": "var(--font-weights-regular)",
    "medium": "var(--font-weights-medium)",
    "semibold": "var(--font-weights-semibold)",
    "bold": "var(--font-weights-bold)"
  },
  "fontSizes": {
    "10": "var(--font-sizes-10)",
    "11": "var(--font-sizes-11)",
    "12": "var(--font-sizes-12)",
    "14": "var(--font-sizes-14)",
    "16": "var(--font-sizes-16)",
    "20": "var(--font-sizes-20)",
    "24": "var(--font-sizes-24)",
    "32": "var(--font-sizes-32)",
    "40": "var(--font-sizes-40)",
    "48": "var(--font-sizes-48)"
  },
  "lineHeights": {
    "tight": "var(--line-heights-tight)",
    "base": "var(--line-heights-base)",
    "relaxed": "var(--line-heights-relaxed)"
  },
  "letterSpacing": {
    "tight": "var(--letter-spacing-tight)",
    "normal": "var(--letter-spacing-normal)"
  },
  "spacing": {
    "0": "var(--spacing-0)",
    "1": "var(--spacing-1)",
    "2": "var(--spacing-2)",
    "3": "var(--spacing-3)",
    "4": "var(--spacing-4)",
    "5": "var(--spacing-5)",
    "6": "var(--spacing-6)",
    "8": "var(--spacing-8)",
    "10": "var(--spacing-10)",
    "12": "var(--spacing-12)",
    "16": "var(--spacing-16)",
    "20": "var(--spacing-20)"
  },
  "borderRadius": {
    "xs": "var(--border-radius-xs)",
    "sm": "var(--border-radius-sm)",
    "md": "var(--border-radius-md)",
    "lg": "var(--border-radius-lg)",
    "xl": "var(--border-radius-xl)",
    "2xl": "var(--border-radius-2xl)",
    "pill": "var(--border-radius-pill)"
  },
  "borderWidth": {
    "thin": "var(--border-width-thin)",
    "medium": "var(--border-width-medium)"
  },
  "boxShadow": {
    "sm": "var(--box-shadow-sm)",
    "md": "var(--box-shadow-md)",
    "lg": "var(--box-shadow-lg)",
    "card": "var(--box-shadow-card)",
    "popup": "var(--box-shadow-popup)"
  },
  "sizing": {
    "icon": {
      "xs": "var(--sizing-icon-xs)",
      "sm": "var(--sizing-icon-sm)",
      "md": "var(--sizing-icon-md)",
      "lg": "var(--sizing-icon-lg)"
    },
    "avatar": {
      "sm": "var(--sizing-avatar-sm)",
      "md": "var(--sizing-avatar-md)",
      "lg": "var(--sizing-avatar-lg)"
    },
    "navHeight": "var(--sizing-nav-height)",
    "cardMin": "var(--sizing-card-min)"
  },
  "breakpoint": {
    "mobile": "var(--breakpoint-mobile)",
    "tablet": "var(--breakpoint-tablet)",
    "desktop": "var(--breakpoint-desktop)",
    "wide": "var(--breakpoint-wide)"
  },
  "motion": {
    "fast": "var(--motion-fast)",
    "normal": "var(--motion-normal)",
    "slow": "var(--motion-slow)"
  },
  "component": {
    "button": {
      "primary": {
        "background": "var(--component-button-primary-background)",
        "backgroundHover": "var(--component-button-primary-background-hover)",
        "backgroundActive": "var(--component-button-primary-background-active)",
        "text": "var(--component-button-primary-text)",
        "radius": "var(--component-button-primary-radius)",
        "height": "var(--component-button-primary-height)",
        "paddingX": "var(--component-button-primary-padding-x)"
      },
      "secondary": {
        "background": "var(--component-button-secondary-background)",
        "text": "var(--component-button-secondary-text)",
        "radius": "var(--component-button-secondary-radius)",
        "height": "var(--component-button-secondary-height)",
        "paddingX": "var(--component-button-secondary-padding-x)"
      },
      "ghost": {
        "background": "var(--component-button-ghost-background)",
        "text": "var(--component-button-ghost-text)",
        "border": "var(--component-button-ghost-border)",
        "radius": "var(--component-button-ghost-radius)",
        "height": "var(--component-button-ghost-height)",
        "paddingX": "var(--component-button-ghost-padding-x)"
      }
    },
    "chip": {
      "default": {
        "background": "var(--component-chip-default-background)",
        "text": "var(--component-chip-default-text)",
        "radius": "var(--component-chip-default-radius)",
        "paddingX": "var(--component-chip-default-padding-x)",
        "paddingY": "var(--component-chip-default-padding-y)"
      },
      "selected": {
        "background": "var(--component-chip-selected-background)",
        "text": "var(--component-chip-selected-text)",
        "radius": "var(--component-chip-selected-radius)"
      },
      "accent": {
        "background": "var(--component-chip-accent-background)",
        "text": "var(--component-chip-accent-text)",
        "radius": "var(--component-chip-accent-radius)"
      }
    },
    "badge": {
      "frontend": {
        "background": "var(--component-badge-frontend-background)",
        "text": "var(--component-badge-frontend-text)"
      },
      "publishing": {
        "background": "var(--component-badge-publishing-background)",
        "text": "var(--component-badge-publishing-text)"
      },
      "design": {
        "background": "var(--component-badge-design-background)",
        "text": "var(--component-badge-design-text)"
      },
      "default": {
        "background": "var(--component-badge-default-background)",
        "text": "var(--component-badge-default-text)"
      },
      "radius": "var(--component-badge-radius)",
      "paddingX": "var(--component-badge-padding-x)",
      "paddingY": "var(--component-badge-padding-y)"
    },
    "card": {
      "default": {
        "background": "var(--component-card-default-background)",
        "border": "var(--component-card-default-border)",
        "radius": "var(--component-card-default-radius)",
        "padding": "var(--component-card-default-padding)",
        "shadow": "var(--component-card-default-shadow)"
      },
      "strong": {
        "background": "var(--component-card-strong-background)",
        "border": "var(--component-card-strong-border)",
        "radius": "var(--component-card-strong-radius)",
        "padding": "var(--component-card-strong-padding)"
      }
    },
    "featureCard": {
      "panelBackground": "var(--component-feature-card-panel-background)",
      "itemBackground": "var(--component-feature-card-item-background)",
      "itemBackgroundDark": "var(--component-feature-card-item-background-dark)",
      "border": "var(--component-feature-card-border)",
      "radius": "var(--component-feature-card-radius)",
      "padding": "var(--component-feature-card-padding)"
    },
    "input": {
      "background": "var(--component-input-background)",
      "border": "var(--component-input-border)",
      "borderFocus": "var(--component-input-border-focus)",
      "text": "var(--component-input-text)",
      "placeholder": "var(--component-input-placeholder)",
      "radius": "var(--component-input-radius)",
      "height": "var(--component-input-height)",
      "paddingX": "var(--component-input-padding-x)"
    },
    "sidebar": {
      "background": "var(--component-sidebar-background)",
      "activeBackground": "var(--component-sidebar-active-background)",
      "activeText": "var(--component-sidebar-active-text)",
      "text": "var(--component-sidebar-text)",
      "radius": "var(--component-sidebar-radius)"
    },
    "navigation": {
      "tabBackground": "var(--component-navigation-tab-background)",
      "tabText": "var(--component-navigation-tab-text)",
      "tabActiveBackground": "var(--component-navigation-tab-active-background)",
      "tabActiveText": "var(--component-navigation-tab-active-text)",
      "radius": "var(--component-navigation-radius)"
    },
    "dashboard": {
      "sectionBackground": "var(--component-dashboard-section-background)",
      "sectionStrongBackground": "var(--component-dashboard-section-strong-background)",
      "title": "var(--component-dashboard-title)",
      "description": "var(--component-dashboard-description)",
      "accentText": "var(--component-dashboard-accent-text)",
      "radius": "var(--component-dashboard-radius)"
    }
  }
};

export const darkTheme = {
  "color": {
    "purple": {
      "25": "var(--color-purple-25)",
      "50": "var(--color-purple-50)",
      "100": "var(--color-purple-100)",
      "200": "var(--color-purple-200)",
      "300": "var(--color-purple-300)",
      "500": "var(--color-purple-500)",
      "600": "var(--color-purple-600)",
      "700": "var(--color-purple-700)",
      "750": "var(--color-purple-750)",
      "800": "var(--color-purple-800)",
      "900": "var(--color-purple-900)",
      "950": "var(--color-purple-950)"
    },
    "blue": {
      "400": "var(--color-blue-400)",
      "500": "var(--color-blue-500)"
    },
    "teal": {
      "50": "var(--color-teal-50)",
      "100": "var(--color-teal-100)",
      "300": "var(--color-teal-300)",
      "500": "var(--color-teal-500)",
      "700": "var(--color-teal-700)",
      "800": "var(--color-teal-800)",
      "900": "var(--color-teal-900)"
    },
    "slate": {
      "100": "var(--color-slate-100)",
      "600": "var(--color-slate-600)",
      "700": "var(--color-slate-700)",
      "800": "var(--color-slate-800)",
      "900": "var(--color-slate-900)"
    },
    "neutral": {
      "0": "var(--color-neutral-0)",
      "50": "var(--color-neutral-50)",
      "100": "var(--color-neutral-100)",
      "300": "var(--color-neutral-300)",
      "400": "var(--color-neutral-400)",
      "500": "var(--color-neutral-500)",
      "700": "var(--color-neutral-700)",
      "800": "var(--color-neutral-800)",
      "900": "var(--color-neutral-900)"
    },
    "glass": {
      "white16": "var(--color-glass-white16)",
      "white72": "var(--color-glass-white72)"
    },
    "brand": {
      "primary": "var(--color-brand-primary)",
      "primaryHover": "var(--color-brand-primary-hover)",
      "primaryActive": "var(--color-brand-primary-active)",
      "secondary": "var(--color-brand-secondary)",
      "soft": "var(--color-brand-soft)",
      "subtle": "var(--color-brand-subtle)"
    },
    "accent": {
      "primary": "var(--color-accent-primary)",
      "deep": "var(--color-accent-deep)",
      "soft": "var(--color-accent-soft)",
      "subtle": "var(--color-accent-subtle)"
    },
    "background": {
      "page": "var(--color-background-page)",
      "card": "var(--color-background-card)",
      "cardStrong": "var(--color-background-card-strong)"
    },
    "surface": {
      "primary": "var(--color-surface-primary)",
      "secondary": "var(--color-surface-secondary)",
      "featurePanel": "var(--color-surface-feature-panel)",
      "featureCard": "var(--color-surface-feature-card)",
      "featureCardDark": "var(--color-surface-feature-card-dark)"
    },
    "text": {
      "primary": "var(--color-text-primary)",
      "secondary": "var(--color-text-secondary)",
      "tertiary": "var(--color-text-tertiary)",
      "inverse": "var(--color-text-inverse)",
      "brand": "var(--color-text-brand)",
      "accent": "var(--color-text-accent)"
    },
    "border": {
      "default": "var(--color-border-default)",
      "strong": "var(--color-border-strong)",
      "focus": "var(--color-border-focus)",
      "accent": "var(--color-border-accent)",
      "feature": "var(--color-border-feature)"
    }
  },
  "fontFamilies": {
    "base": "var(--font-families-base)",
    "fallback": "var(--font-families-fallback)"
  },
  "fontWeights": {
    "regular": "var(--font-weights-regular)",
    "medium": "var(--font-weights-medium)",
    "semibold": "var(--font-weights-semibold)",
    "bold": "var(--font-weights-bold)"
  },
  "fontSizes": {
    "10": "var(--font-sizes-10)",
    "11": "var(--font-sizes-11)",
    "12": "var(--font-sizes-12)",
    "14": "var(--font-sizes-14)",
    "16": "var(--font-sizes-16)",
    "20": "var(--font-sizes-20)",
    "24": "var(--font-sizes-24)",
    "32": "var(--font-sizes-32)",
    "40": "var(--font-sizes-40)",
    "48": "var(--font-sizes-48)"
  },
  "lineHeights": {
    "tight": "var(--line-heights-tight)",
    "base": "var(--line-heights-base)",
    "relaxed": "var(--line-heights-relaxed)"
  },
  "letterSpacing": {
    "tight": "var(--letter-spacing-tight)",
    "normal": "var(--letter-spacing-normal)"
  },
  "spacing": {
    "0": "var(--spacing-0)",
    "1": "var(--spacing-1)",
    "2": "var(--spacing-2)",
    "3": "var(--spacing-3)",
    "4": "var(--spacing-4)",
    "5": "var(--spacing-5)",
    "6": "var(--spacing-6)",
    "8": "var(--spacing-8)",
    "10": "var(--spacing-10)",
    "12": "var(--spacing-12)",
    "16": "var(--spacing-16)",
    "20": "var(--spacing-20)"
  },
  "borderRadius": {
    "xs": "var(--border-radius-xs)",
    "sm": "var(--border-radius-sm)",
    "md": "var(--border-radius-md)",
    "lg": "var(--border-radius-lg)",
    "xl": "var(--border-radius-xl)",
    "2xl": "var(--border-radius-2xl)",
    "pill": "var(--border-radius-pill)"
  },
  "borderWidth": {
    "thin": "var(--border-width-thin)",
    "medium": "var(--border-width-medium)"
  },
  "boxShadow": {
    "sm": "var(--box-shadow-sm)",
    "md": "var(--box-shadow-md)",
    "lg": "var(--box-shadow-lg)",
    "card": "var(--box-shadow-card)",
    "popup": "var(--box-shadow-popup)"
  },
  "sizing": {
    "icon": {
      "xs": "var(--sizing-icon-xs)",
      "sm": "var(--sizing-icon-sm)",
      "md": "var(--sizing-icon-md)",
      "lg": "var(--sizing-icon-lg)"
    },
    "avatar": {
      "sm": "var(--sizing-avatar-sm)",
      "md": "var(--sizing-avatar-md)",
      "lg": "var(--sizing-avatar-lg)"
    },
    "navHeight": "var(--sizing-nav-height)",
    "cardMin": "var(--sizing-card-min)"
  },
  "breakpoint": {
    "mobile": "var(--breakpoint-mobile)",
    "tablet": "var(--breakpoint-tablet)",
    "desktop": "var(--breakpoint-desktop)",
    "wide": "var(--breakpoint-wide)"
  },
  "motion": {
    "fast": "var(--motion-fast)",
    "normal": "var(--motion-normal)",
    "slow": "var(--motion-slow)"
  },
  "component": {
    "button": {
      "primary": {
        "background": "var(--component-button-primary-background)",
        "backgroundHover": "var(--component-button-primary-background-hover)",
        "backgroundActive": "var(--component-button-primary-background-active)",
        "text": "var(--component-button-primary-text)",
        "radius": "var(--component-button-primary-radius)",
        "height": "var(--component-button-primary-height)",
        "paddingX": "var(--component-button-primary-padding-x)"
      },
      "secondary": {
        "background": "var(--component-button-secondary-background)",
        "text": "var(--component-button-secondary-text)",
        "radius": "var(--component-button-secondary-radius)",
        "height": "var(--component-button-secondary-height)",
        "paddingX": "var(--component-button-secondary-padding-x)"
      },
      "ghost": {
        "background": "var(--component-button-ghost-background)",
        "text": "var(--component-button-ghost-text)",
        "border": "var(--component-button-ghost-border)",
        "radius": "var(--component-button-ghost-radius)",
        "height": "var(--component-button-ghost-height)",
        "paddingX": "var(--component-button-ghost-padding-x)"
      }
    },
    "chip": {
      "default": {
        "background": "var(--component-chip-default-background)",
        "text": "var(--component-chip-default-text)",
        "radius": "var(--component-chip-default-radius)",
        "paddingX": "var(--component-chip-default-padding-x)",
        "paddingY": "var(--component-chip-default-padding-y)"
      },
      "selected": {
        "background": "var(--component-chip-selected-background)",
        "text": "var(--component-chip-selected-text)",
        "radius": "var(--component-chip-selected-radius)"
      },
      "accent": {
        "background": "var(--component-chip-accent-background)",
        "text": "var(--component-chip-accent-text)",
        "radius": "var(--component-chip-accent-radius)"
      }
    },
    "badge": {
      "frontend": {
        "background": "var(--component-badge-frontend-background)",
        "text": "var(--component-badge-frontend-text)"
      },
      "publishing": {
        "background": "var(--component-badge-publishing-background)",
        "text": "var(--component-badge-publishing-text)"
      },
      "design": {
        "background": "var(--component-badge-design-background)",
        "text": "var(--component-badge-design-text)"
      },
      "default": {
        "background": "var(--component-badge-default-background)",
        "text": "var(--component-badge-default-text)"
      },
      "radius": "var(--component-badge-radius)",
      "paddingX": "var(--component-badge-padding-x)",
      "paddingY": "var(--component-badge-padding-y)"
    },
    "card": {
      "default": {
        "background": "var(--component-card-default-background)",
        "border": "var(--component-card-default-border)",
        "radius": "var(--component-card-default-radius)",
        "padding": "var(--component-card-default-padding)",
        "shadow": "var(--component-card-default-shadow)"
      },
      "strong": {
        "background": "var(--component-card-strong-background)",
        "border": "var(--component-card-strong-border)",
        "radius": "var(--component-card-strong-radius)",
        "padding": "var(--component-card-strong-padding)"
      }
    },
    "featureCard": {
      "panelBackground": "var(--component-feature-card-panel-background)",
      "itemBackground": "var(--component-feature-card-item-background)",
      "itemBackgroundDark": "var(--component-feature-card-item-background-dark)",
      "border": "var(--component-feature-card-border)",
      "radius": "var(--component-feature-card-radius)",
      "padding": "var(--component-feature-card-padding)"
    },
    "input": {
      "background": "var(--component-input-background)",
      "border": "var(--component-input-border)",
      "borderFocus": "var(--component-input-border-focus)",
      "text": "var(--component-input-text)",
      "placeholder": "var(--component-input-placeholder)",
      "radius": "var(--component-input-radius)",
      "height": "var(--component-input-height)",
      "paddingX": "var(--component-input-padding-x)"
    },
    "sidebar": {
      "background": "var(--component-sidebar-background)",
      "activeBackground": "var(--component-sidebar-active-background)",
      "activeText": "var(--component-sidebar-active-text)",
      "text": "var(--component-sidebar-text)",
      "radius": "var(--component-sidebar-radius)"
    },
    "navigation": {
      "tabBackground": "var(--component-navigation-tab-background)",
      "tabText": "var(--component-navigation-tab-text)",
      "tabActiveBackground": "var(--component-navigation-tab-active-background)",
      "tabActiveText": "var(--component-navigation-tab-active-text)",
      "radius": "var(--component-navigation-radius)"
    },
    "dashboard": {
      "sectionBackground": "var(--component-dashboard-section-background)",
      "sectionStrongBackground": "var(--component-dashboard-section-strong-background)",
      "title": "var(--component-dashboard-title)",
      "description": "var(--component-dashboard-description)",
      "accentText": "var(--component-dashboard-accent-text)",
      "radius": "var(--component-dashboard-radius)"
    }
  }
};

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};

export default lightTheme;
