import fs from "fs";
import path from "path";

const rootDir = process.cwd();

const tokenPaths = {
  single: path.join(rootDir, "tokens", "portfolio-tokens.json"),
  core: path.join(rootDir, "tokens", "core.json"),
  light: path.join(rootDir, "tokens", "semantic-light.json"),
  dark: path.join(rootDir, "tokens", "semantic-dark.json"),
  component: path.join(rootDir, "tokens", "component.json"),
};

const outputPath = path.join(rootDir, "src", "styles", "tokens.css");

function readJson(filePath) {
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function toKebabCase(text) {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function pathToVariableName(tokenPath) {
  return `--${tokenPath.split(".").map(toKebabCase).join("-")}`;
}

function resolveValue(value) {
  if (typeof value !== "string") return value;

  const exactRef = value.match(/^\{(.+)\}$/);
  if (!exactRef) return value;

  return `var(${pathToVariableName(exactRef[1])})`;
}

function flattenSet(obj, prefix = []) {
  const result = {};

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const nextPrefix = [...prefix, key];

    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      "value" in value
    ) {
      const variableName = `--${nextPrefix.map(toKebabCase).join("-")}`;
      result[variableName] = resolveValue(value.value);
    } else if (value && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(result, flattenSet(value, nextPrefix));
    }
  }

  return result;
}

function formatCssBlock(selector, sections) {
  const body = sections
    .filter(({ variables }) => Object.keys(variables).length > 0)
    .map(({ comment, variables }) => {
      const lines = Object.entries(variables).map(
        ([name, value]) => `  ${name}: ${value};`
      );
      return [`  /* ${comment} */`, ...lines].join("\n");
    })
    .join("\n\n");

  return `${selector} {\n${body}\n}`;
}

function loadTokenSets() {
  const singleFile = readJson(tokenPaths.single);

  if (singleFile) {
    return {
      core: singleFile.core || {},
      light: singleFile["semantic-light"] || {},
      dark: singleFile["semantic-dark"] || {},
      component: singleFile.component || {},
    };
  }

  return {
    core: readJson(tokenPaths.core) || {},
    light: readJson(tokenPaths.light) || {},
    dark: readJson(tokenPaths.dark) || {},
    component: readJson(tokenPaths.component) || {},
  };
}

function buildCssTokens() {
  const { core, light, dark, component } = loadTokenSets();

  const coreVariables = flattenSet(core);
  const lightVariables = flattenSet(light);
  const darkVariablesAll = flattenSet(dark);
  const componentVariables = flattenSet(component);

  const darkVariables = {};
  for (const [name, value] of Object.entries(darkVariablesAll)) {
    if (lightVariables[name] !== value) {
      darkVariables[name] = value;
    }
  }

  const css = [
    "/* This file is auto-generated from design tokens. */",
    "/* Do not edit this file manually. */",
    "",
    formatCssBlock(":root", [
      { comment: "Core", variables: coreVariables },
      { comment: "Semantic (light)", variables: lightVariables },
      { comment: "Component", variables: componentVariables },
    ]),
    "",
    formatCssBlock('[data-theme="dark"]', [
      { comment: "Semantic (dark overrides)", variables: darkVariables },
    ]),
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, css, "utf8");

  console.log(`Generated CSS variables: ${outputPath}`);
}

export default buildCssTokens;