const fs = require("fs");
const path = require("path");

const rootDir = process.cwd();

const tokenPaths = {
  single: path.join(rootDir, "tokens", "portfolio-tokens.json"),
  core: path.join(rootDir, "tokens", "core.json"),
  light: path.join(rootDir, "tokens", "semantic-light.json"),
  dark: path.join(rootDir, "tokens", "semantic-dark.json"),
  component: path.join(rootDir, "tokens", "component.json"),
};

const outputPath = path.join(rootDir, "src", "styles", "theme.js");

function readJson(filePath) {
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function deepMerge(...objects) {
  const result = {};

  for (const obj of objects) {
    if (!obj) continue;

    for (const key of Object.keys(obj)) {
      const value = obj[key];

      if (
        value &&
        typeof value === "object" &&
        !Array.isArray(value) &&
        !("value" in value)
      ) {
        result[key] = deepMerge(result[key] || {}, value);
      } else {
        result[key] = value;
      }
    }
  }

  return result;
}

function toKebabCase(text) {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function createThemeObject(obj, prefix = []) {
  const result = {};

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const nextPrefix = [...prefix, key];

    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      "value" in value
    ) {
      const cssVariableName = `--${nextPrefix.map(toKebabCase).join("-")}`;
      result[key] = `var(${cssVariableName})`;
    } else if (value && typeof value === "object" && !Array.isArray(value)) {
      result[key] = createThemeObject(value, nextPrefix);
    }
  }

  return result;
}

function loadTokenSets() {
  const singleFile = readJson(tokenPaths.single);

  if (singleFile) {
    return {
      core: singleFile.core || {},
      light: singleFile["semantic-light"] || {},
      dark: singleFile["semantic-dark"] || {},
      component: singleFile.component || {},
    };
  }

  return {
    core: readJson(tokenPaths.core) || {},
    light: readJson(tokenPaths.light) || {},
    dark: readJson(tokenPaths.dark) || {},
    component: readJson(tokenPaths.component) || {},
  };
}

function buildTheme() {
  const { core, light, dark, component } = loadTokenSets();

  const lightTokens = deepMerge(core, light, component);
  const darkTokens = deepMerge(core, dark, component);

  const lightTheme = createThemeObject(lightTokens);
  const darkTheme = createThemeObject(darkTokens);

  const themeFile = `/* This file is auto-generated from design tokens. */
/* Do not edit this file manually. */

export const lightTheme = ${JSON.stringify(lightTheme, null, 2)};

export const darkTheme = ${JSON.stringify(darkTheme, null, 2)};

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};

export default lightTheme;
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, themeFile, "utf8");

  console.log(`Generated theme object: ${outputPath}`);
}

if (require.main === module) {
  buildTheme();
}

module.exports = buildTheme;
