const fs = require("fs");
const path = require("path");

const rootDir = process.cwd();

const tokenPaths = {
  single: path.join(rootDir, "tokens", "portfolio-tokens.json"),
  core: path.join(rootDir, "tokens", "core.json"),
  light: path.join(rootDir, "tokens", "semantic-light.json"),
  dark: path.join(rootDir, "tokens", "semantic-dark.json"),
  component: path.join(rootDir, "tokens", "component.json"),
};

const outputPath = path.join(rootDir, "src", "styles", "tokens.css");

function readJson(filePath) {
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function deepMerge(...objects) {
  const result = {};

  for (const obj of objects) {
    if (!obj) continue;

    for (const key of Object.keys(obj)) {
      const value = obj[key];

      if (
        value &&
        typeof value === "object" &&
        !Array.isArray(value) &&
        !("value" in value)
      ) {
        result[key] = deepMerge(result[key] || {}, value);
      } else {
        result[key] = value;
      }
    }
  }

  return result;
}

function getTokenByPath(obj, tokenPath) {
  const keys = tokenPath.split(".");
  let current = obj;

  for (const key of keys) {
    if (!current || typeof current !== "object") return null;
    current = current[key];
  }

  return current;
}

function resolveValue(value, tokenObject, stack = []) {
  if (typeof value !== "string") return value;

  const exactRef = value.match(/^\{(.+)\}$/);

  if (!exactRef) return value;

  const refPath = exactRef[1];

  if (stack.includes(refPath)) {
    console.warn(`Circular token reference found: ${stack.join(" -> ")} -> ${refPath}`);
    return value;
  }

  const refToken = getTokenByPath(tokenObject, refPath);

  if (!refToken || !("value" in refToken)) {
    console.warn(`Missing token reference: ${refPath}`);
    return value;
  }

  return resolveValue(refToken.value, tokenObject, [...stack, refPath]);
}

function toKebabCase(text) {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

function flattenTokens(obj, tokenObject, prefix = []) {
  const result = {};

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const nextPrefix = [...prefix, key];

    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      "value" in value
    ) {
      const variableName = `--${nextPrefix.map(toKebabCase).join("-")}`;
      result[variableName] = resolveValue(value.value, tokenObject);
    } else if (value && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(result, flattenTokens(value, tokenObject, nextPrefix));
    }
  }

  return result;
}

function formatCssBlock(selector, variables) {
  const lines = Object.entries(variables).map(
    ([name, value]) => `  ${name}: ${value};`
  );

  return `${selector} {\n${lines.join("\n")}\n}`;
}

function loadTokenSets() {
  const singleFile = readJson(tokenPaths.single);

  if (singleFile) {
    return {
      core: singleFile.core || {},
      light: singleFile["semantic-light"] || {},
      dark: singleFile["semantic-dark"] || {},
      component: singleFile.component || {},
    };
  }

  return {
    core: readJson(tokenPaths.core) || {},
    light: readJson(tokenPaths.light) || {},
    dark: readJson(tokenPaths.dark) || {},
    component: readJson(tokenPaths.component) || {},
  };
}

function buildCssTokens() {
  const { core, light, dark, component } = loadTokenSets();

  const lightTokens = deepMerge(core, light, component);
  const darkTokens = deepMerge(core, dark, component);

  const lightVariables = flattenTokens(lightTokens, lightTokens);
  const darkVariablesAll = flattenTokens(darkTokens, darkTokens);

  const darkVariables = {};

  for (const [name, value] of Object.entries(darkVariablesAll)) {
    if (lightVariables[name] !== value) {
      darkVariables[name] = value;
    }
  }

  const css = [
    "/* This file is auto-generated from design tokens. */",
    "/* Do not edit this file manually. */",
    "",
    formatCssBlock(":root", lightVariables),
    "",
    formatCssBlock('[data-theme="dark"]', darkVariables),
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, css, "utf8");

  console.log(`Generated CSS variables: ${outputPath}`);
}

if (require.main === module) {
  buildCssTokens();
}

module.exports = buildCssTokens;